export const INITIAL_CATEGORIES = [
  { id: 1, name: 'Technology & Coding', slug: 'technology-coding', description: 'Software engineering, AI, algorithms, and system design.' },
  { id: 2, name: 'Business & Leadership', slug: 'business-leadership', description: 'Management, venture strategy, innovation, and economics.' },
  { id: 3, name: 'Science & Engineering', slug: 'science-engineering', description: 'Quantum physics, biology, mathematics, and aerospace.' },
  { id: 4, name: 'Design & Architecture', slug: 'design-architecture', description: 'UI/UX design systems, typography, and structural art.' },
  { id: 5, name: 'Philosophy & Essays', slug: 'philosophy-essays', description: 'Critical thinking, ethics, and contemporary thought.' }
];

export const INITIAL_DOCUMENTS = [
  {
    id: 1,
    title: 'Building Enterprise Applications with Spring Boot & Oracle',
    author: 'Dr. Sarah Vance',
    description: 'A comprehensive guide to building resilient, cloud-native microservices backed by enterprise Oracle database clusters and modern web architectures.',
    categoryId: 1,
    categoryName: 'Technology & Coding',
    categorySlug: 'technology-coding',
    fileName: 'spring-boot-oracle-guide.pdf',
    originalFilename: 'spring-boot-oracle-guide.pdf',
    fileSize: 3472,
    fileType: 'application/pdf',
    coverImagePath: '',
    pageCount: 4,
    language: 'English',
    publishedYear: 2025,
    isFeatured: true,
    isPublished: true,
    viewCount: 142,
    downloadCount: 38,
    uploadedByUsername: 'Sourav',
    createdAt: '09-09-2026 15:28:40',
    updatedAt: '09-09-2026 15:28:40'
  },
  {
    id: 2,
    title: "The Innovator's Architecture: Scaling High-Impact Teams",
    author: 'Marcus Thorne',
    description: 'Strategic patterns for scaling engineering organizations, cultivating high-performance culture, and driving sustainable business velocity.',
    categoryId: 2,
    categoryName: 'Business & Leadership',
    categorySlug: 'business-leadership',
    fileName: 'innovators-architecture.pdf',
    originalFilename: 'innovators-architecture.pdf',
    fileSize: 2770,
    fileType: 'application/pdf',
    coverImagePath: '',
    pageCount: 3,
    language: 'English',
    publishedYear: 2024,
    isFeatured: true,
    isPublished: true,
    viewCount: 98,
    downloadCount: 24,
    uploadedByUsername: 'Sourav',
    createdAt: '09-09-2026 15:28:40',
    updatedAt: '09-09-2026 15:28:40'
  },
  {
    id: 3,
    title: 'Foundations of Quantum Computing & Information Theory',
    author: 'Elena Rostova, Ph.D.',
    description: 'An accessible yet rigorous exploration of quantum mechanics, qubits, entanglement, quantum algorithms, and future computing horizons.',
    categoryId: 3,
    categoryName: 'Science & Engineering',
    categorySlug: 'science-engineering',
    fileName: 'quantum-computing-foundations.pdf',
    originalFilename: 'quantum-computing-foundations.pdf',
    fileSize: 4215,
    fileType: 'application/pdf',
    coverImagePath: '',
    pageCount: 5,
    language: 'English',
    publishedYear: 2026,
    isFeatured: false,
    isPublished: true,
    viewCount: 65,
    downloadCount: 19,
    uploadedByUsername: 'Sourav',
    createdAt: '09-09-2026 15:28:40',
    updatedAt: '09-09-2026 15:28:40'
  }
];
