-- ==========================================================
-- Oracle Database DDL Schema for Scribd-like Document Platform
-- Compatible with Oracle 19c, 21c, 23ai & Oracle Free/XE
-- ==========================================================

-- 1. USERS TABLE
CREATE TABLE USERS (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'ROLE_USER' NOT NULL,
    FULL_NAME VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. CATEGORIES TABLE
CREATE TABLE CATEGORIES (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL UNIQUE,
    SLUG VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(500),
    ICON VARCHAR2(50) DEFAULT 'book'
);

-- 3. DOCUMENTS / BOOKS TABLE
CREATE TABLE DOCUMENTS (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    AUTHOR VARCHAR2(150) NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    CATEGORY_ID NUMBER(19) NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    ORIGINAL_FILENAME VARCHAR2(255) NOT NULL,
    FILE_SIZE NUMBER(19) DEFAULT 0 NOT NULL,
    FILE_TYPE VARCHAR2(50) DEFAULT 'application/pdf',
    COVER_IMAGE_PATH VARCHAR2(255),
    PAGE_COUNT NUMBER(10) DEFAULT 1,
    LANGUAGE VARCHAR2(30) DEFAULT 'English',
    PUBLISHED_YEAR NUMBER(5),
    IS_FEATURED NUMBER(1) DEFAULT 0 NOT NULL,
    IS_PUBLISHED NUMBER(1) DEFAULT 1 NOT NULL,
    VIEW_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
    DOWNLOAD_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
    UPLOADED_BY NUMBER(19) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_DOC_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DOC_UPLOADER FOREIGN KEY (UPLOADED_BY) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- 4. READING HISTORY TABLE
CREATE TABLE READING_HISTORY (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    DOCUMENT_ID NUMBER(19) NOT NULL,
    LAST_PAGE NUMBER(10) DEFAULT 1 NOT NULL,
    PROGRESS_PERCENT NUMBER(5,2) DEFAULT 0.00,
    LAST_READ_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_RH_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RH_DOC FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_RH_USER_DOC UNIQUE (USER_ID, DOCUMENT_ID)
);

-- 5. BOOKMARKS TABLE
CREATE TABLE BOOKMARKS (
    ID NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    DOCUMENT_ID NUMBER(19) NOT NULL,
    PAGE_NUMBER NUMBER(10) DEFAULT 1 NOT NULL,
    NOTE VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_BM_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_BM_DOC FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENTS(ID) ON DELETE CASCADE
);

-- Indexes for optimal lookup performance
CREATE INDEX IDX_DOCS_CATEGORY ON DOCUMENTS(CATEGORY_ID);
CREATE INDEX IDX_DOCS_FEATURED ON DOCUMENTS(IS_FEATURED);
CREATE INDEX IDX_DOCS_PUBLISHED ON DOCUMENTS(IS_PUBLISHED);
CREATE INDEX IDX_DOCS_CREATED ON DOCUMENTS(CREATED_AT DESC);
